In [15]:
# 1. IMPORT LIBRARY
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [16]:
# 2. MEMUAT DATASET IRIS
iris = load_iris()

In [17]:
# X: Fitur (4 kolom numerik)
X = iris.data

In [18]:
# Y: Label (Target/Spesies: 0, 1, 2)
Y = iris.target

In [19]:
print("Tipe data X (Fitur): \n", X.dtype)
print("Bentuk data X (Baris, Kolom):", X.shape)
print("5 Baris Data X Awal:\n", X[:5])

Tipe data X (Fitur): 
 float64
Bentuk data X (Baris, Kolom): (150, 4)
5 Baris Data X Awal:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [20]:
# 3. ENCODING LABEL (Y)
# Label (Y) sudah numerik, tapi kita gunakan LabelEncoder untuk memastikan
le = LabelEncoder()
Y_encoded = le.fit_transform(Y)

print("Label Y (Target) setelah di-encode (5 baris pertama):\n", Y_encoded[:5])

Label Y (Target) setelah di-encode (5 baris pertama):
 [0 0 0 0 0]


In [21]:
# 4. PEMBAGIAN DATA (TRAIN-TEST SPLIT)
# Membagi X dan Y (yang sudah di-encode)
# random_state=42 digunakan agar pembagian selalu sama setiap kali dijalankan
X_train, X_test, y_train, y_test = train_test_split(X, Y_encoded, test_size = 0.2, random_state = 42)

print(f"Total Data: {len(X)}")
print(f"Data Training (80%): {len(X_train)} baris")
print(f"Data Testing (20%): {len(X_test)} baris")

Total Data: 150
Data Training (80%): 120 baris
Data Testing (20%): 30 baris


In [22]:
# 5. FEATURE SCALING (STANDARDISASI)
sc = StandardScaler()

# Melatih dan menerapkan scaler pada Training Set (fit_transform)
# Ini menghitung nilai rata-rata dan standar deviasi dari X_train.
X_train_scaled = sc.fit_transform(X_train)

# Menerapkan scaler pada Testing Set (transform)
# Menggunakan nilai rata-rata dan standar deviasi dari X_train.
X_test_scaled = sc.transform(X_test)

print("X_train SEBELUM Scaling (5 baris pertama):\n", X_train[:5])
print("\nX_train SETELAH Scaling (5 baris pertama):")
# Nilai-nilai sekarang berada di sekitar 0 (nilai negatif dan positif kecil)
print(X_train_scaled[:5])

X_train SEBELUM Scaling (5 baris pertama):
 [[4.6 3.6 1.  0.2]
 [5.7 4.4 1.5 0.4]
 [6.7 3.1 4.4 1.4]
 [4.8 3.4 1.6 0.2]
 [4.4 3.2 1.3 0.2]]

X_train SETELAH Scaling (5 baris pertama):
[[-1.47393679  1.20365799 -1.56253475 -1.31260282]
 [-0.13307079  2.99237573 -1.27600637 -1.04563275]
 [ 1.08589829  0.08570939  0.38585821  0.28921757]
 [-1.23014297  0.75647855 -1.2187007  -1.31260282]
 [-1.7177306   0.30929911 -1.39061772 -1.31260282]]
